#### all caregories
GET http://localhost:7004/api/category/allCategory
Content-Type: application/json

#### create category
POST http://localhost:7004/api/category/createCategory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI5YTQ0YzZhODBhODFlYzk0NGZiMzYiLCJmaXJzdE5hbWUiOiJHaHVsYW0gSG9zc2VpbiIsImxhc3ROYW1lIjoiS2FyaW1pIiwiZW1haWwiOiJrYXJpbWlhbWlyaG9zc2VpbjEyQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImN1c3RvbWVyTnVtYmVyIjoiR0syMDgwIiwib3duZXIiOmZhbHNlLCJkZWZhdWx0QWRkcmVzcyI6eyJzdHJlZXQiOiJ2YW4tcmVjdW0tU3RyYcOfZSIsImhvdXNlTnVtYmVyIjoiNTQiLCJjaXR5IjoiQmFkIEtyZXV6bmFjaCIsInppcCI6IjU1NTQ1IiwiY291bnRyeSI6IkRldXRzY2hsYW5kIiwicGhvbmUiOiIwMTcwNzQwNzQxNyJ9LCJpYXQiOjE3NzM5MTY1NTUsImV4cCI6MTc3MzkxNzQ1NX0.6qtxmxyU85KDUAgszj37Lc175yXR0PeEbipo6pihV3U

{
  "name": "T-shirt",
  "description": "string",
  "image": "string",
  "gender" : "Kinder"
}

#### update category
PUT http://localhost:7004/api/category/682dac0c1e5d8b655255ca0f
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFiNDY5YTNhZWUxOWY3ZTUzY2UxMjkiLCJmaXJzdE5hbWUiOiJSZXphIiwibGFzdE5hbWUiOiJSYWhpbWkiLCJlbWFpbCI6InJhaGltaS45MDE3MTlAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzQ3ODIzNjAxLCJleHAiOjE3NDc4MjQ1MDF9.pLAVNt7qWuKiO__Xglz330RHDt9_f4bRi0q8Ut-6Slw

{
  "name": "Jacke",
  "description": "string",
  "image": "string",
  "gender" : "Männlich"
}


