#### create category
POST http://localhost:7004/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI5YTQ0YzZhODBhODFlYzk0NGZiMzYiLCJmaXJzdE5hbWUiOiJHaHVsYW0gSG9zc2VpbiIsImxhc3ROYW1lIjoiS2FyaW1pIiwiZW1haWwiOiJrYXJpbWlhbWlyaG9zc2VpbjEyQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImN1c3RvbWVyTnVtYmVyIjoiR0syMDgwIiwib3duZXIiOmZhbHNlLCJkZWZhdWx0QWRkcmVzcyI6eyJzdHJlZXQiOiJ2YW4tcmVjdW0tU3RyYcOfZSIsImhvdXNlTnVtYmVyIjoiNTQiLCJjaXR5IjoiQmFkIEtyZXV6bmFjaCIsInppcCI6IjU1NTQ1IiwiY291bnRyeSI6IkRldXRzY2hsYW5kIiwicGhvbmUiOiIwMTcwNzQwNzQxNyJ9LCJpYXQiOjE3NzM5MTExOTMsImV4cCI6MTc3MzkxMjA5M30.tDVPNlcsuwnPN0nuR384kGc-8kN7f2qsDGzHVZT21oI

{
  "name": "Winterjacke",
  "description": "Warme Jacke für den Winter",
  "price": 99.99,
  "image": "default-image.jpg",
  "category": "682dac0c1e5d8b655255ca0f",
  "stock": 50,
  "colors": [
  { "name": "Schwarz", "hexCode": "#000000" },
  { "name": "Blau", "hexCode": "#0000FF" }
],
"weight": 1.5
}

#### create product (mit Sharp-Verarbeitung)
### Produkt erstellen mit echtem Bild (für Sharp Test)
POST http://localhost:7004/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI5YTQ0YzZhODBhODFlYzk0NGZiMzYiLCJmaXJzdE5hbWUiOiJHaHVsYW0gSG9zc2VpbiIsImxhc3ROYW1lIjoiS2FyaW1pIiwiZW1haWwiOiJrYXJpbWlhbWlyaG9zc2VpbjEyQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImN1c3RvbWVyTnVtYmVyIjoiR0syMDgwIiwib3duZXIiOmZhbHNlLCJkZWZhdWx0QWRkcmVzcyI6eyJzdHJlZXQiOiJ2YW4tcmVjdW0tU3RyYcOfZSIsImhvdXNlTnVtYmVyIjoiNTQiLCJjaXR5IjoiQmFkIEtyZXV6bmFjaCIsInppcCI6IjU1NTQ1IiwiY291bnRyeSI6IkRldXRzY2hsYW5kIiwicGhvbmUiOiIwMTcwNzQwNzQxNyJ9LCJpYXQiOjE3NzM5MTM1MzMsImV4cCI6MTc3MzkxNDQzM30.NjndXSkWILqZaDk13Dhu4Ee84NljsGD7PsPDENNfaRQ
Content-Type: multipart/form-data; boundary=WebPTest

--WebPTest
Content-Disposition: form-data; name="name"

Winterjacke
--WebPTest
Content-Disposition: form-data; name="description"

Warme Jacke für den Winter
--WebPTest
Content-Disposition: form-data; name="price"

99.99
--WebPTest
Content-Disposition: form-data; name="category"

682dac0c1e5d8b655255ca0f
--WebPTest
Content-Disposition: form-data; name="stock"

50
--WebPTest
Content-Disposition: form-data; name="weight"

1.5
--WebPTest
Content-Disposition: form-data; name="colors"

[{"name":"Schwarz","hexCode":"#000000"}]
--WebPTest
Content-Disposition: form-data; name="images"; filename="image2.jpg"
Content-Type: image/jpeg

< C:\Users\karim\OneDrive\Pictures\image2.jpg
--WebPTest--

#### get all products
GET http://localhost:7004/api/products
Content-Type: application/json

#### delete product
DELETE http://localhost:7004/api/products/6852cc7722130fdd2d92b155
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFiNDY5YTNhZWUxOWY3ZTUzY2UxMjkiLCJmaXJzdE5hbWUiOiJSZXphIiwibGFzdE5hbWUiOiJSYWhpbWkiLCJlbWFpbCI6InJhaGltaS45MDE3MTlAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzUwMjU2MTkyLCJleHAiOjE3NTAyNTcwOTJ9.5oZFZP8brLCYDg6Z9WxNgjEbZAaIOE2OrDJamGqCnIg

#### update product
PUT http://localhost:7004/api/products/683d977f35061f47aa8efe65
Content-Type: application/json
