#### register user
POST http://localhost:7004/api/user/register
Content-Type: application/json

{
    "firstName": "Reza",
    "lastName": "Rahimi",
    "email": "rahimi.901719@gmail.com",
    "password": "Asra.2020!",
    "confirmPassword": "Asra.2020!"
}

#### login user
POST  http://localhost:7004/api/user/login
Content-Type: application/json

{
    "email": "rahimi.901719@gmail.com",
    "password": "Asra.2020!"
}

#### Owner abrufen
GET http://localhost:7004/api/user/getOwner
Content-Type: application/json


### Me abrufen
GET http://localhost:7004/api/user/me
Content-Type: application/json

### Refresh Token testen
POST http://localhost:7004/api/user/refresh-token
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZmNDc4MGY4NWZhNjQxNTZlNmEzYzAiLCJmaXJzdE5hbWUiOiJHaHVsYW0iLCJsYXN0TmFtZSI6IkthcmltaSIsImVtYWlsIjoia2FyaW1pQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc0NjUzNjExOSwiZXhwIjoxNzQ2NTM3MDE5fQ.woJlpZLOhdLWYdDaEyG1NnSE8mG7xrqaJcB6dUdWObg


### edit user
PUT http://localhost:7004/api/user/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTk0YjNlNjAxMTg0NTAxYTg3NzAwYmUiLCJlbWFpbCI6InJhaGltaXouOTAxNzE5QGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IlJlenphIiwibGFzdE5hbWUiOiJSYWhpbWkiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzcxMzUzMjAxLCJleHAiOjE3NzEzNTQxMDF9.Rs3wdwHHa-awC1RsivGMTclXwDPf6koMuZjrhiKvbsM

{
  "firstName": "Reza",
  "lastName": "Rahimi",
  "defaultAddress": {
    "fullName": "Reza Rahimi",
    "houseNumber": "54",
    "street": "Brückes",
    "city": "Bad Kreuznach",
    "zip": "55545",
    "country": "Deutschland",
    "phone": "+49 1707407417"
  }
}




#### user logout
DELETE http://localhost:7004/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZmNDc4MGY4NWZhNjQxNTZlNmEzYzAiLCJlbWFpbCI6ImthcmltaUBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJHaHVsYW0iLCJsYXN0TmFtZSI6IkthcmltaSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NDQ3ODM1NjcsImV4cCI6MTc0NDc4NDQ2N30.iLJ28-kLAIsuNXfqS0vd4AumwuILrWvoDbX8NXmrGNw

#### get users
GET http://localhost:7004/api/user/all
Content-Type: application/json